name: CI/CD Pipeline
on:
  push:
    branches: [main]
  Vb:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run test || true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: $${secrets.VERCEL_TOKEN}}
          VERCEL_PROJECT_ID: $${secrets.VERCEL_PROJECT_ID}}
          VERCEL_ORG_ID: $${secrets.VERCEL_ORG_ID}}
        run: npx vercel --prod --token=$VERCEL_TOKEN
